### ISSUE TITLE
Is it possible to add batch case conversion for tags?

### ISSUE THREAD

**Issue by eipi10** [thalient-ai/zotero-scripts#1]
In the Batch Tagging script, would it be possible to add an option to convert all tags in the selected collection to lower case? Zotero tags seem to be case sensitive and I'm finding a lot cases of multiple tags that are the same, except for case, but are treated as separate tags. It would be great to be able to just convert them all to lower case so that they become a single tag.

**Comment by thalient-ai** [comment]
Done, I've added the text-case functionality to the batch tag script

**Comment by eipi10** [comment]
Great! Thanks!
